# Generated by Django 5.2.7 on 2025-10-24 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link this employee to a login user (non-staff).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='month',
            field=models.DateField(help_text='Store as first day of month (YYYY-MM-01)'),
        ),
    ]
